### ISSUE TITLE
How to make Training Date with Multi-class segmentation

### ISSUE THREAD

**Issue by zhDai** [avBuffer/UNet3plus_pth#4]
HI，can u tell me how to make training data about masks if I  try Multi-class segmentation

**Comment by wangfusheng-cqu** [comment]
Did you solve it?

**Comment by zhDai** [comment]
> Did you solve it?

yeah，just label different classes with different colors

**Comment by csuhp201** [comment]
> > Did you solve it?
> 
> yeah，just label different classes with different colors

how do you solve it? can we discuss it with qq or wechat？
